//{{NO_DEPENDENCIES}}
// $loctext_autogeneratedinclude$
// $loctext_autogeneratedincludeusedby$ $projectname$.rc

#define IDS_APP_TITLE			103

[!if WIN_APP]
#define IDR_MAINFRAME			128
#define IDD_$safercprojectname$_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_$safercprojectname$			107
#define IDI_SMALL				108
#define IDC_$safercprojectname$			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// $loctext_nextresource$
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

[!if !SUPPORT_MFC]
#define _APS_NO_MFC					130
[!endif]
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
[!else]
// $loctext_nextresource$
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	101
#define _APS_NEXT_COMMAND_VALUE		40001
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#endif
#endif
[!endif]
